---
#
name: 'ns'
run_name: 'NS'

dataset: 'NS'
# fno2d
modes: 64
width: 32
depth: 4

# training
learning_rate: 1e-3
weight_decay: 1e-4

batch_size: 5
epochs: 101

n_train: 20
n_test: 5
n_selfcon: 20
epochs_selfcon: 10 # now epochs_selfcon is the epoch to start self-consistency loss
epoch_test: 5

S: 256
T: 300
sub_s: 1
sub_t: 1

#grid_size: 128

# datasets
data_dir: '/media/wumming/HHD/HHD_data/KF/'

train_data: 'KF_f0_Re1000_N25_T500_S256_part0.pt'
train_re:
test_data: ['KF_f0_Re250_N25_T500_S256_part0.pt',
            'KF_f0_Re500_N25_T500_S256_part0.pt',
            'KF_f0_Re1000_N25_T500_S256_part0.pt',
            'KF_f0_Re2000_N25_T500_S256_part0.pt',
            'KF_f0_Re4000_N25_T500_S256_part0.pt']
test_re:
selfcon_data:

#
augmentation_loss: False
use_augmentation:
