---
#
name: 'default'

# fno2d
modes: 20
width: 32
depth: 4

# training
learning_rate: 1e-3
weight_decay: 1e-4
batch_size: 16
epochs: 200

n_train: 1024
n_test: 128
n_selfcon: 1024
epochs_selfcon: 50 # now epochs_selfcon is the epoch to start self-consistency loss
#grid_size: 128

# datasets
data_dir: '/central/groups/astuart/slanth/SymmetryNO/Dirichlet_bc_nonzero/data'
train_data: 'darcy_BC_Nsamp1024_Ns128_alphacoeff3.00_alphag3.00.mat'
test_data: 'darcy_test_BC_Nsamp1024_Ns128_alphacoeff3.00_alphag3.00.mat'
selfcon_data:

#
augmentation_loss: False
use_augmentation:
