---
#
name: 'helmholtz'
run_name: 'helmholtz'
dataset: 'helmholtz'

# fno2d
modes: 20
width: 32
depth: 4

# training
learning_rate: 1e-3
weight_decay: 1e-4
batch_size: 16
epochs: 200

n_train: 1024
n_test: 128
n_selfcon: 1024
epochs_selfcon: 50 # now epochs_selfcon is the epoch to start self-consistency loss
epoch_test: 1

# datasets
data_dir: '/media/wumming/HHD/HHD_data/helmholtz/data'

train_data: 'helmholtz_BC_k25_tanh_amin1.0_amax12.0_Nsamp1024_Ns257_alphacoeff1.50_alphag3.50.mat'
test_data: ['helmholtz_test_BC_k5_tanh_amin1.0_amax12.0_Nsamp128_Ns65_alphacoeff1.50_alphag3.50.mat',
            'helmholtz_test_BC_k10_tanh_amin1.0_amax12.0_Nsamp128_Ns129_alphacoeff1.50_alphag3.50.mat',
            'helmholtz_test_BC_k25_tanh_amin1.0_amax12.0_Nsamp128_Ns257_alphacoeff1.50_alphag3.50.mat',
            'helmholtz_test_BC_k50_tanh_amin1.0_amax12.0_Nsamp128_Ns513_alphacoeff1.50_alphag3.50.mat',
            'helmholtz_test_BC_k100_tanh_amin1.0_amax12.0_Nsamp128_Ns1025_alphacoeff1.50_alphag3.50.mat']
selfcon_data:

#
augmentation_loss: False
use_augmentation:
