---
#
name: 'helmholtz'
run_name: 'helmholtz SC'
dataset: 'helmholtz'

# fno2d
model: "FNO_u" # "UNet", "FNO", "FNO_re"

modes: 64
width: 32
depth: 2
level: 2
mlp: False

# training
learning_rate: 1e-3
weight_decay: 1e-4
batch_size: 8
epochs: 2

n_train: 8
n_test: 8
n_selfcon: 8
epochs_selfcon: 1 # now epochs_selfcon is the epoch to start self-consistency loss
epoch_test: 5

#grid_size: 128
S: 256

# datasets
data_dir: '/media/wumming/HHD/HHD_data/helmholtz/data'
#data_dir: '/central/groups/astuart/zongyi/helmholtz/data'



train_data: [
#'helmholtz_BC_k5_lognormal_amin0.0_amax0.0_Nsamp1024_Ns65_alphacoeff1.50_alphag3.50.mat',
#'helmholtz_BC_k10_lognormal_amin0.0_amax0.0_Nsamp1024_Ns129_alphacoeff1.50_alphag3.50.mat',
'helmholtz_BC_k25_lognormal_amin0.0_amax0.0_Nsamp1024_Ns257_alphacoeff1.50_alphag3.50.mat',
]

train_re: [25,]

test_data: [
  'helmholtz_test_BC_k1_lognormal_amin0.0_amax0.0_Nsamp128_Ns65_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k2_lognormal_amin0.0_amax0.0_Nsamp128_Ns65_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k5_lognormal_amin0.0_amax0.0_Nsamp128_Ns65_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k10_lognormal_amin0.0_amax0.0_Nsamp128_Ns129_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k25_lognormal_amin0.0_amax0.0_Nsamp128_Ns257_alphacoeff1.50_alphag3.50.mat',
#  'helmholtz_test_BC_k50_lognormal_amin0.0_amax0.0_Nsamp128_Ns513_alphacoeff1.50_alphag3.50.mat',
#  'helmholtz_test_BC_k100_lognormal_amin0.0_amax0.0_Nsamp128_Ns1025_alphacoeff1.50_alphag3.50.mat',
]
#test_re: [25,]
test_re: [1,2,5,10,25]
selfcon_data:
selfcon_re:
#
augmentation_loss: 1
augmentation_samples: 1
use_augmentation:
sample_virtual_instance: 1
