---
#
name: 'helmholtz_uno'
run_name: 'Helmholtz UNO'
dataset: 'helmholtz'

model: "UNO"
modes: 64
width: 32
depth: 4
level: 2
mlp: False
scale_informed: True
frequency_pos_emb: True
uno_out_channels: [32, 64, 64, 32]
uno_n_modes: [[20,20], [20,20], [20,20], [20,20]]
uno_scalings: [[1,1], [0.5,0.5], [1,1], [2,2]]
channel_mlp_skip: "linear"

# training
learning_rate: 1e-3
weight_decay: 1e-4
batch_size: 16
epochs: 200

n_train: 1024
n_test: 128
n_selfcon: 1024
epochs_selfcon: 50 # now epochs_selfcon is the epoch to start self-consistency loss
epoch_test: 1

S: 128

# datasets
data_dir: '/pscratch/sd/z/zongyili/mhchen/helmholtz/data'

train_data: [
'helmholtz_BC_k5_lognormal_amin0.0_amax0.0_Nsamp1024_Ns65_alphacoeff1.50_alphag3.50.mat',
'helmholtz_BC_k10_lognormal_amin0.0_amax0.0_Nsamp1024_Ns129_alphacoeff1.50_alphag3.50.mat',
'helmholtz_BC_k25_lognormal_amin0.0_amax0.0_Nsamp1024_Ns257_alphacoeff1.50_alphag3.50.mat',
]
train_re: [5,10,25,]

test_data: [
  'helmholtz_test_BC_k1_lognormal_amin0.0_amax0.0_Nsamp128_Ns65_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k2_lognormal_amin0.0_amax0.0_Nsamp128_Ns65_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k5_lognormal_amin0.0_amax0.0_Nsamp128_Ns65_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k10_lognormal_amin0.0_amax0.0_Nsamp128_Ns129_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k25_lognormal_amin0.0_amax0.0_Nsamp128_Ns257_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k50_lognormal_amin0.0_amax0.0_Nsamp128_Ns513_alphacoeff1.50_alphag3.50.mat',
  'helmholtz_test_BC_k100_lognormal_amin0.0_amax0.0_Nsamp128_Ns1025_alphacoeff1.50_alphag3.50.mat',
]
test_re: [1,2,5,10,25,50,100]
selfcon_data:
selfcon_re:

#
augmentation_loss: 0
augmentation_samples: 2
use_augmentation:
sample_virtual_instance: 0
